name: CI 

on: 
  [ push, workflow_dispatch ]

permissions:
  contents: read
  packages: read
      
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    # 12.8.3 was the latest version with a full installer. 12.8.4 is a patch release, which requires 
    # a base installation on top of which >= 12.8.4 is installed.
    strategy:
      matrix:
        version: [ 12.8.3, 12.8.8 ]
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          path: src

      - name: Get OpenEdge version
        id: get-oeversion
        uses: bfv/openedge-flatversion@49ecdca1670447fcf715c0b505607ec17dc59b62  # v1.2.1
        with:
          version: ${{matrix.version}}

      - name: Version to env
        run: |
          echo "FLATVERSION=${{ steps.get-oeversion.outputs.flat-version }}" >> $GITHUB_ENV
          echo "OPENEDGE_VERSION=${{matrix.version}}" >> $GITHUB_ENV
          echo "OPENEDGE_BASE_VERSION=${{ steps.get-oeversion.outputs.base-version }}" >> $GITHUB_ENV
  
      - name: Insert JDK version in Dockerfile
        run: |
          jdk=`jq -r ".jdk${FLATVERSION}" src/jdk-versions.json`
          echo JDK: $jdk
          sed -i "s/JDKVERSION/$jdk/g" src/Dockerfile-gh
          echo download jdk from Dockerfile:
          cat src/Dockerfile | grep temurin
  
      - name: Download installer files
        run: |
          src/scripts/download-openedge.sh
      
      - name: Get response.ini  # get progress.cfg from secret PROGRESS_CFG_122
        run: |
          echo fetching response.ini/progress.cfg from secret RESPONSE_INI_${{env.FLATVERSION}}
          echo "${{ secrets[format('RESPONSE_INI_{0}', env.FLATVERSION)] }}" > src/response.ini
          echo "${{ secrets[format('PROGRESS_CFG_{0}', env.FLATVERSION)] }}" | base64 --decode > src/progress.cfg
          ls -l src

      - name: Build docker image
        run: |
          cd src
          docker build -f Dockerfile-gh -t openedge-db:${{env.OPENEDGE_VERSION}} .

      - name: Remove installer files
        run: |
          cd src
          rm -f PROGRESS_*
          rm response.ini
          ls -l 
      